PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX proj: <http://imce.jpl.nasa.gov/foundation/project#>
PREFIX org: <http://opencaesar.io/organizations/nasa#>

Select ?proj ?org ?Mission
WHERE {
  ?s rdf:type proj:Project .
  ?s rdfs:label ?proj . 
  ?s proj:isResponsibilityOf ?o . 
  ?o rdfs:label ?org .
  ?s proj:supplies ?m .
  ?m rdfs:label ?Mission
} ORDER BY ?proj