PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX project: <http://imce.jpl.nasa.gov/foundation/project#>
PREFIX mission: <http://imce.jpl.nasa.gov/foundation/mission#>
PREFIX org: <http://opencaesar.io/organizations/nasa#>
PREFIX pr: <http://purl.org/ontology/prv/core#>
PREFIX pro: <http://purl.org/hpi/patchr#>

Select ?wp ?subpackage ?subSupply ?subOrg
WHERE {
  ?p a project:Project.
  ?p project:authorizes ?w.
  ?w a project:WorkPackage .
  ?w rdfs:label ?wp .
  ?w project:authorizes ?sp .
  ?sp rdfs:label ?subpackage .
  ?sp project:supplies ?sps .
  ?sps rdfs:label ?subSupply .
  ?sp project:isResponsibilityOf ?spo.
  ?spo rdfs:label ?subOrg
} ORDER BY ?subpackage