PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX project: <http://imce.jpl.nasa.gov/foundation/project#>
PREFIX mission: <http://imce.jpl.nasa.gov/foundation/mission#>
PREFIX org: <http://opencaesar.io/organizations/nasa#>

Select ?mission ?holder
WHERE {
  ?m a mission:Mission . 
  ?m rdfs:label ?mission .
  ?m mission:pursues ?p .
  ?s project:represents ?p .
  ?s rdfs:label ?holder
}